# -*- coding: utf-8 -*-
"""Supply Chain Risk Monitoring without LLMEnrichment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjx9_D3pNErMdlPaco2X36VuDTUvf7gY
"""

"""
Indian Army Supply Chain Risk Monitor
====================================================
• Deterministic baseline scoring — no LLM, no live web search, no cloud APIs
• Plotly interactive dashboard (multi-panel: risk scores, tables, ownership, alternates)
• Full ownership CSV integration with SOE-keyword detection and stake-depth filtering
• Supplier rollup (multi-vehicle / multi-component aggregation)
• Dynamic country-crisis filter via interactive prompt
"""

# ── CELL 1: Install ───────────────────────────────────────────
# !pip install -q plotly pandas pyyaml

# ── CELL 2: Backend Config ────────────────────────────────────
import os

OWNERSHIP_DEPTH_PCT = 1   # show ownership stakes ≥ this %

# ── CELL 3: CSV Loaders ────────────────────────────────────────────────────────
import pandas as pd

def _get_local_or_upload(path_hint: str, label: str) -> str:
    if os.path.exists(path_hint):
        print(f"✅ Found {label} at {path_hint}")
        return path_hint
    try:
        from google.colab import files
        print(f"⬆️  Please upload {label} (.csv) in the dialog that appears below...")
        uploaded = files.upload()
        if not uploaded:
            raise FileNotFoundError(f"No file uploaded for {label}")
        return list(uploaded.keys())[0]
    except ImportError:
        raise FileNotFoundError(f"{label} not found at {path_hint}.")


def load_supply_chain_csv(path_hint="/content/supply_chain.csv") -> list:
    """
    Load the supply chain Neo4j export.
    Expected columns: vehicle, component (or category+component_name),
    tier1_supplier, tier1_country, tier2_supplier, tier2_country
    """
    fp = _get_local_or_upload(path_hint, "supply_chain.csv")
    df = pd.read_csv(fp)
    graph = []
    for _, row in df.iterrows():
        tier2_supplier = row.get("tier2_supplier")
        tier1_supplier = row.get("tier1_supplier")
        if pd.isna(tier2_supplier) or str(tier2_supplier).strip() == "":
            tier2_supplier = tier1_supplier
            tier2_country  = row.get("tier1_country")
        else:
            tier2_country = row.get("tier2_country")

        component_label = row.get("tier2_component")
        if pd.isna(component_label) or str(component_label).strip() == "":
            component_label = row.get("component", row.get("component_name", row.get("function", "")))

        graph.append({
            "vehicle":    str(row.get("vehicle", "")),
            "component":  str(component_label),
            "tier2":      str(tier2_supplier),
            "tier1":      str(tier1_supplier),
            "t2_country": str(tier2_country)  if not pd.isna(tier2_country)  else "Unknown",
            "t1_country": str(row.get("tier1_country", "Unknown")),
        })
    print(f"✅ Loaded {len(graph)} supply chain edges from {fp}")
    return graph, df          # return raw df too for rollup


def load_ownership_csv(path_hint="/content/ownership.csv") -> dict:
    """
    Load the ownership Neo4j export.
    Key column can be named 'supplier' OR 'tier1_supplier' (both handled).
    Other columns: owner, owner_type / owner_node_type, owner_country, stake_pct, note / board_role
    """
    fp = _get_local_or_upload(path_hint, "ownership.csv")
    df = pd.read_csv(fp)
    registry: dict = {}
    for _, row in df.iterrows():
        supplier = row.get("supplier") if not pd.isna(row.get("supplier", float("nan"))) \
                   else row.get("tier1_supplier")
        if supplier is None or (isinstance(supplier, float) and pd.isna(supplier)):
            continue
        supplier = str(supplier).strip()

        stake = row.get("stake_pct")
        try:
            stake = float(stake) if not pd.isna(stake) else 0.0
        except (TypeError, ValueError):
            stake = 0.0

        owner_type = row.get("owner_type")
        if pd.isna(owner_type):
            owner_type = row.get("owner_node_type", "Unknown")

        board_role = row.get("board_role", row.get("note", ""))
        if pd.isna(board_role):
            board_role = ""

        entry = {
            "owner":      str(row.get("owner", "Unknown")),
            "type":       str(owner_type),
            "country":    str(row.get("owner_country", "Unknown")),
            "stake_pct":  stake,
            "board_role": str(board_role),
        }
        registry.setdefault(supplier, []).append(entry)

    print(f"✅ Loaded ownership records for {len(registry)} suppliers from {fp}")
    return registry, df       # return raw df too for SOE rollup


# ── CELL 4: Load data ─────────────────────────────────────────
NEO4J_GRAPH,        SUPPLY_DF  = load_supply_chain_csv()
OWNERSHIP_REGISTRY, OWNER_DF   = load_ownership_csv()

print(f"\nGraph edges       : {len(NEO4J_GRAPH)}")
print(f"Ownership suppliers: {len(OWNERSHIP_REGISTRY)}")


# ── CELL 5: Build supplier rollup ─────────────────────────────
import re

SOE_KEYWORDS = re.compile(
    r"government|sovereign|state|gic|temasek|bpifrance|lic of india|soe|"
    r"public sector|national investment|pension fund|insurer",
    re.I,
)

_owner_col = "tier1_supplier" if "tier1_supplier" in OWNER_DF.columns else "supplier"
OWNER_DF["is_state_linked"] = (
    OWNER_DF["owner_type"].astype(str).str.contains(SOE_KEYWORDS) |
    OWNER_DF["owner"].astype(str).str.contains(SOE_KEYWORDS)
)

soe_summary_df = (
    OWNER_DF[OWNER_DF["is_state_linked"]]
    .groupby(_owner_col)
    .agg(
        max_state_stake=("stake_pct", "max"),
        state_owners=("owner", lambda s: ", ".join(sorted(set(s)))),
    )
    .reset_index()
    .rename(columns={_owner_col: "supplier"})
)
soe_summary_df["soe_status"] = soe_summary_df["max_state_stake"].apply(
    lambda p: "Controlled" if p >= 25 else "Linked"
)
print(f"State-linked Tier-1 suppliers (SOE keyword scan): {len(soe_summary_df)}")

_records = []
for _, r in SUPPLY_DF.iterrows():
    t1 = str(r.get("tier1_supplier", ""))
    t2 = str(r.get("tier2_supplier", ""))
    t1c = str(r.get("tier1_country", "Unknown"))
    t2c = str(r.get("tier2_country", "Unknown"))
    comp = str(r.get("component", r.get("component_name", "")))
    veh  = str(r.get("vehicle", ""))

    if t1:
        _records.append({"supplier": t1, "tier": "Tier-1", "country": t1c, "vehicle": veh, "component": comp})
    if t2 and t2 != t1 and t2.strip() not in ("", "nan"):
        _records.append({"supplier": t2, "tier": "Tier-2", "country": t2c, "vehicle": veh, "component": comp})

supplier_registry_df = pd.DataFrame(_records).drop_duplicates(subset=["supplier", "vehicle", "component"])

SUPPLIER_ROLLUP = (
    supplier_registry_df.groupby("supplier")
    .agg(
        countries=("country",    lambda s: sorted(set(s))),
        vehicles =("vehicle",    lambda s: sorted(set(s))),
        components=("component", lambda s: sorted(set(s))),
        tiers    =("tier",       lambda s: sorted(set(s))),
    )
    .reset_index()
    .merge(
        soe_summary_df[["supplier", "soe_status", "state_owners", "max_state_stake"]],
        on="supplier", how="left",
    )
)

print(f"Total unique suppliers in portfolio: {len(SUPPLIER_ROLLUP)}")


# ── CELL 6: Optional CREAO config loading ─────────────────────
import yaml, json as _json

def _try_load(path_hint, label, loader):
    if os.path.exists(path_hint):
        try:
            with open(path_hint, "r", encoding="utf-8") as f:
                return loader(f)
        except Exception as e:
            print(f"⚠️ Couldn't parse {label}: {e}")
    return None

CREAO_CONFIG   = _try_load("/content/config.yaml",   "config.yaml",   yaml.safe_load)
CREAO_MANIFEST = _try_load("/content/manifest.json",  "manifest.json", _json.load)

AGENT_TITLE = (CREAO_MANIFEST or {}).get("name", "Indian Army Supply Chain Risk Monitor")

_DEPTH_MAP = {"one_percent": 1, "five_percent": 5, "ten_percent": 10, "twenty_five_percent": 25}
if CREAO_CONFIG:
    for field in CREAO_CONFIG.get("form", {}).get("fields", []):
        if field.get("id") == "ownership_depth":
            OWNERSHIP_DEPTH_PCT = _DEPTH_MAP.get(field.get("default_value"), OWNERSHIP_DEPTH_PCT)
    print(f"✅ CREAO config.yaml — ownership depth set to ≥{OWNERSHIP_DEPTH_PCT}%")


# ── CELL 7: Ownership Analysis Engine ────────────────────────
STATE_TYPES = {
    "Government", "Sovereign Wealth Fund", "Government Investment",
    "Government Pension Fund", "Government Insurer", "SOE", "Industrial Conglomerate",
    "Public Sector",
}

def run_ownership_analysis(suppliers: list, registry: dict, depth_pct: float = 1.0) -> list:
    results = []
    for s in suppliers:
        name = s.get("name", "")
        owners = registry.get(name, [])
        flagged_owners = [o for o in owners if o["stake_pct"] >= depth_pct]

        state_owners = [
            o for o in flagged_owners
            if o["type"] in STATE_TYPES or SOE_KEYWORDS.search(o["type"]) or SOE_KEYWORDS.search(o["owner"])
        ]
        total_state_pct = min(sum(o["stake_pct"] for o in state_owners), 100)
        soe_flag = (
            any(o["stake_pct"] > 25 and (o["type"] in STATE_TYPES or SOE_KEYWORDS.search(o["type"])) for o in flagged_owners)
            or total_state_pct > 40
        )
        results.append({
            **s,
            "owners":            flagged_owners,
            "state_owners":      state_owners,
            "total_state_pct":   round(total_state_pct, 1),
            "soe_flag":          soe_flag,
            "ownership_risk_score": min(20, int(total_state_pct / 5)),
        })
    return results


# ── CELL 8: Cost premium lookup ───────────────────────────────
# Countries are grouped by strategic proximity to India.
# This gives each alternate a realistic, varied cost premium
# instead of a flat 12% for every single alternate.

_ALLIED_COUNTRIES = {
    "India", "Russia", "Israel", "France", "United States", "USA",
    "UK", "United Kingdom", "Japan", "South Korea", "Australia",
}
_NEUTRAL_COUNTRIES = {
    "Germany", "Italy", "Sweden", "Spain", "Brazil", "Singapore",
    "Malaysia", "Turkey", "UAE", "South Africa",
}

def _cost_premium_pct(supplier_name: str, country: str) -> int:
    """
    Returns a varied cost-premium estimate based on the alternate
    supplier's country and a deterministic offset from the supplier name,
    so each row shows a different realistic value.
    """
    # Name-hash gives a small ±offset so identical-country alternates still differ
    name_offset = sum(ord(c) for c in supplier_name) % 7  # 0-6

    if country in _ALLIED_COUNTRIES:
        base = 8
    elif country in _NEUTRAL_COUNTRIES:
        base = 18
    else:
        base = 28   # non-allied / unknown geography → higher premium

    return base + name_offset   # e.g. 8-14% for India, 18-24% neutral, 28-34% other


# ── CELL 9: Plotly Dashboard ──────────────────────────────────
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import datetime
from IPython.display import display, HTML
from collections import defaultdict


def render_dashboard(analysis: dict, ownership_data: list):
    suppliers        = analysis.get("suppliers", [])
    alternates       = analysis.get("alternate_suppliers", [])
    score            = analysis.get("portfolio_risk_score", 0)
    level            = analysis.get("overall_risk_level", "UNKNOWN")
    crisis_countries = ", ".join(analysis.get("crisis_countries", ["Unknown"]))

    def rcol(v):
        return "#ef4444" if v >= 70 else "#f59e0b" if v >= 50 else "#22c55e"

    suppliers_sorted = sorted(suppliers, key=lambda x: x.get("risk_score", 0), reverse=True)
    soe_flagged      = [o for o in ownership_data if o.get("soe_flag")]

    # ── Layout: 4 rows (scatter removed) ─────────────────────
    fig = make_subplots(
        rows=4, cols=2,
        subplot_titles=(
            f"📊 Supplier Risk Scores — Crisis: {crisis_countries}",
            "🔄 Alternate Supplier Readiness Scores",
            "🚛 Full Supplier Risk Register (All Vehicles)", "",
            f"🏛️ Ownership Analysis — State Stakes ≥{OWNERSHIP_DEPTH_PCT}%", "",
            "🔷 Neo4j Graph — Ownership Chain (SOE Flags)", "",
        ),
        specs=[
            [{"type": "bar"},                        {"type": "bar"}],
            [{"type": "table", "colspan": 2},        None],
            [{"type": "table", "colspan": 2},        None],
            [{"type": "table", "colspan": 2},        None],
        ],
        vertical_spacing=0.06,
        row_heights=[0.20, 0.22, 0.30, 0.28],
        column_widths=[0.55, 0.45],
    )

    # ── Row 1-col-1: Supplier risk bar chart ─────────────────
    fig.add_trace(go.Bar(
        x=[s["name"] for s in suppliers_sorted],
        y=[s.get("risk_score", 0) for s in suppliers_sorted],
        marker_color=[rcol(s.get("risk_score", 0)) for s in suppliers_sorted],
        text=[str(s.get("risk_score", 0)) for s in suppliers_sorted],
        textposition="outside", showlegend=False, name="Risk Score",
    ), row=1, col=1)
    fig.add_hline(y=70, line_dash="dash", line_color="#f59e0b",
                  annotation_text="Alert Threshold (70)", row=1, col=1)

    # ── Row 1-col-2: Alternate readiness bar ─────────────────
    top_alts = sorted(alternates, key=lambda x: x.get("readiness_score", 0), reverse=True)[:8]
    fig.add_trace(go.Bar(
        x=[a["name"] for a in top_alts],
        y=[a.get("readiness_score", 0) for a in top_alts],
        marker_color=["#22c55e" if a.get("readiness_score", 0) >= 80 else "#f59e0b" for a in top_alts],
        text=[str(a.get("readiness_score", 0)) for a in top_alts],
        textposition="outside", showlegend=False, name="Readiness",
    ), row=1, col=2)

    # ── Row 2: Full supplier risk register table ──────────────
    fig.add_trace(go.Table(
        header=dict(
            values=["<b>Supplier</b>", "<b>Country</b>", "<b>Component</b>", "<b>Vehicle</b>",
                    "<b>Tier</b>", "<b>Risk Score</b>", "<b>Reason</b>", "<b>Status</b>"],
            fill_color="#1e293b", font=dict(color="white", size=10), align="left", height=26,
        ),
        cells=dict(values=[
            [s["name"] for s in suppliers_sorted],
            [s.get("country", "?") for s in suppliers_sorted],
            [s.get("component", "?") for s in suppliers_sorted],
            [s.get("vehicle", "?") for s in suppliers_sorted],
            [f"Tier {s.get('tier', 1)}" for s in suppliers_sorted],
            [s.get("risk_score", 0) for s in suppliers_sorted],
            [s.get("risk_reason", "") for s in suppliers_sorted],
            ["🔴 CRITICAL" if s.get("risk_score", 0) >= 70
             else "🟡 MEDIUM" if s.get("risk_score", 0) >= 50 else "🟢 LOW"
             for s in suppliers_sorted],
        ],
        fill_color=[[
            "#fee2e2" if s.get("risk_score", 0) >= 70
            else "#fef9c3" if s.get("risk_score", 0) >= 50 else "#dcfce7"
            for s in suppliers_sorted
        ]] * 8,
        font=dict(size=9), align="left", height=20),
    ), row=2, col=1)

    # ── Row 3: Ownership table + Alternates table (side by side → now ownership full-width) ──
    # Ownership table (full-width)
    own_rows = []
    for o in ownership_data:
        for owner in o.get("owners", []):
            flag = (
                "🚨 SOE FLAG"
                if o.get("soe_flag") and (
                    owner["type"] in STATE_TYPES or SOE_KEYWORDS.search(owner["type"]) or SOE_KEYWORDS.search(owner["owner"])
                )
                else "✅ OK"
            )
            own_rows.append({
                "supplier": o["name"], "owner": owner["owner"], "type": owner["type"],
                "country": owner["country"], "stake": owner["stake_pct"],
                "board": owner.get("board_role", ""), "flag": flag,
            })
    fig.add_trace(go.Table(
        header=dict(
            values=["<b>Supplier</b>", "<b>Owner</b>", "<b>Type</b>", "<b>Country</b>",
                    f"<b>Stake %</b><br><sub>(≥{OWNERSHIP_DEPTH_PCT}% shown)</sub>",
                    "<b>Board Role</b>", "<b>Flag</b>"],
            fill_color="#7c3aed", font=dict(color="white", size=10), align="left", height=26,
        ),
        cells=dict(values=[
            [r["supplier"] for r in own_rows], [r["owner"] for r in own_rows],
            [r["type"] for r in own_rows],     [r["country"] for r in own_rows],
            [f"{r['stake']}%" for r in own_rows],
            [r["board"] for r in own_rows],    [r["flag"] for r in own_rows],
        ],
        fill_color=[["#fde8ff" if "SOE" in r["flag"] else "#f0fdf4" for r in own_rows]] * 7,
        font=dict(size=9), align="left", height=20),
    ), row=3, col=1)

    # ── Row 4: Alternates summary table (full-width) ──────────
    top12 = sorted(alternates, key=lambda x: x.get("readiness_score", 0), reverse=True)[:12]
    fig.add_trace(go.Table(
        header=dict(
            values=["<b>Replaces</b>", "<b>Alternate Supplier</b>", "<b>Country</b>",
                    "<b>Readiness</b>", "<b>Lead (wks)</b>", "<b>+Cost%</b>", "<b>Reason</b>"],
            fill_color="#0f766e", font=dict(color="white", size=10), align="left", height=26,
        ),
        cells=dict(values=[
            [a.get("replaces", "")                for a in top12],
            [a.get("name", "")                    for a in top12],
            [a.get("country", "")                 for a in top12],
            [f"{a.get('readiness_score', 0)}/100" for a in top12],
            [a.get("lead_time_weeks", 0)          for a in top12],
            [f"+{a.get('cost_premium_pct', 0)}%"  for a in top12],
            [a.get("reason", "")                  for a in top12],
        ],
        fill_color=[["#d1fae5" if a.get("readiness_score", 0) >= 80 else "#fef9c3" for a in top12]] * 7,
        font=dict(size=9), align="left", height=20),
    ), row=4, col=1)

    fig.update_layout(
        title=dict(
            text=(
                f"🇮🇳 {AGENT_TITLE.upper()}<br>"
                f"<sup>Scenario: {analysis.get('scenario_summary', '')[:90]}  |  "
                f"Crisis Countries: {crisis_countries}  |  Risk: {score}/100 — {level}  |  "
                f"{datetime.datetime.now().strftime('%Y-%m-%d %H:%M')} UTC</sup>"
            ),
            font=dict(size=14), x=0.5, xanchor="center",
        ),
        height=1800, paper_bgcolor="#f8fafc",
        font=dict(family="Inter, sans-serif", size=10),
        margin=dict(t=100, b=40, l=40, r=60),
    )
    fig.update_xaxes(tickangle=-35, row=1, col=1)
    fig.update_xaxes(tickangle=-35, row=1, col=2)

    # ── Neo4j ownership chain section in Row 4 (appended after alternates table)
    neo4j_rows = []
    for o in ownership_data:
        for st in o.get("state_owners", []):
            if st["stake_pct"] >= OWNERSHIP_DEPTH_PCT:
                neo4j_rows.append({
                    "cypher": (
                        f"(:{st['type']}{{name:'{st['owner']}'}})"
                        f"-[:OWNS{{pct:{st['stake_pct']}}}]->"
                        f"(Supplier{{name:'{o['name']}'}})"
                    ),
                    "supplier": o["name"], "owner": st["owner"],
                    "type": st["type"],   "pct":   st["stake_pct"],
                    "flag": "🚨 SOE" if o["soe_flag"] else "⚠️ Watch",
                })

    fig.show()

    # ── HTML KPI panel ────────────────────────────────────────
    alerts_html = "".join(
        f'<div style="background:#fee2e2;border-left:4px solid #ef4444;padding:6px 10px;'
        f'margin:3px 0;border-radius:4px;font-size:11px;">🚨 {a}</div>'
        for a in analysis.get("critical_alerts", []))
    actions_html = "".join(
        f"<li style='margin:2px 0;font-size:11px;'>{a}</li>"
        for a in analysis.get("immediate_actions", []))
    soe_html = "".join(
        f'<div style="background:#fde8ff;border-left:4px solid #7c3aed;padding:6px 10px;'
        f'margin:3px 0;border-radius:4px;font-size:11px;">⚠️ {o["name"]} — '
        f'State stake: {o["total_state_pct"]}% — '
        f'SOE FLAG: {"YES 🚨" if o["soe_flag"] else "Watch"}</div>'
        for o in ownership_data if o.get("state_owners"))
    kpi_cards = "".join(f"""
    <div style="background:#1e293b;padding:9px 16px;border-radius:8px;min-width:120px;text-align:center;">
      <div style="font-size:9px;color:#94a3b8;text-transform:uppercase;">{label}</div>
      <div style="font-size:22px;font-weight:700;color:{color};">{value}</div>
    </div>""" for label, value, color in [
        ("Portfolio Risk",    f"{score}/100",      "#ef4444" if score >= 70 else "#f59e0b"),
        ("Risk Level",        level,               "#ef4444" if level == "CRITICAL" else "#f59e0b"),
        ("Suppliers",         len(suppliers),      "#60a5fa"),
        ("Critical Alerts",   len(analysis.get("critical_alerts", [])), "#ef4444"),
        ("SOE Flags",         len(soe_flagged),    "#a78bfa"),
        ("Alternates Found",  len(alternates),     "#22c55e"),
        ("Ownership Depth",   f"≥{OWNERSHIP_DEPTH_PCT}%", "#f59e0b"),
    ])
    display(HTML(f"""
    <div style="font-family:Inter,sans-serif;padding:14px;background:#0f172a;color:white;border-radius:10px;margin:10px 0;">
      <h2 style="margin:0 0 10px;font-size:15px;">🛡️ {AGENT_TITLE}
        &nbsp;<span style="font-size:11px;color:#64748b;">Crisis: {crisis_countries}</span></h2>
      <div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px;">{kpi_cards}</div>
      <p style="font-size:11px;color:#cbd5e1;margin:6px 0 10px;">{analysis.get("executive_summary", "")}</p>
      <div style="display:flex;gap:10px;flex-wrap:wrap;">
        <div style="flex:1;min-width:240px;background:#1e293b;padding:10px;border-radius:8px;">
          <div style="color:#f87171;font-size:10px;font-weight:700;margin-bottom:4px;">🔴 CRITICAL ALERTS</div>
          {alerts_html or '<div style="font-size:11px;color:#94a3b8;">None triggered</div>'}
        </div>
        <div style="flex:1;min-width:240px;background:#1e293b;padding:10px;border-radius:8px;">
          <div style="color:#4ade80;font-size:10px;font-weight:700;margin-bottom:4px;">✅ IMMEDIATE ACTIONS</div>
          <ul style="margin:0;padding-left:14px;">{actions_html}</ul>
        </div>
        <div style="flex:1;min-width:240px;background:#1e293b;padding:10px;border-radius:8px;">
          <div style="color:#c084fc;font-size:10px;font-weight:700;margin-bottom:4px;">🏛️ OWNERSHIP FLAGS (≥{OWNERSHIP_DEPTH_PCT}%)</div>
          {soe_html or '<div style="font-size:11px;color:#94a3b8;">No state-linked owners above threshold</div>'}
        </div>
      </div>
    </div>
    """))
    return fig


# ── CELL 10: Dynamic Country-Crisis Filter ────────────────────
raw_countries = set()

for edge in NEO4J_GRAPH:
    for key in ["t1_country", "t2_country"]:
        val = edge.get(key)
        if val and str(val).strip().lower() not in ("unknown", "nan", ""):
            raw_countries.add(str(val).strip())

for entries in OWNERSHIP_REGISTRY.values():
    for entry in entries:
        val = entry.get("country")
        if val and str(val).strip().lower() not in ("unknown", "nan", ""):
            raw_countries.add(str(val).strip())

available_countries = sorted(raw_countries)

print("\n🌍 Countries found in your data:")
if not available_countries:
    print("  ⚠️ No country columns detected — enter a country name manually below.")
else:
    for idx, ctry in enumerate(available_countries, 1):
        print(f"  [{idx}] {ctry}")
print("──────────────────────────────────────────────────")

selection = input("\nEnter country name or number to set as Crisis Zone: ").strip()
if selection.isdigit() and 1 <= int(selection) <= len(available_countries):
    CRISIS_COUNTRY = available_countries[int(selection) - 1]
else:
    matched = [c for c in available_countries if c.lower() == selection.lower()]
    CRISIS_COUNTRY = matched[0] if matched else selection

print(f"\n🚨 Crisis country set to: {CRISIS_COUNTRY}")


# ── CELL 11: Deterministic baseline agent ─────────────────────
def run_baseline_country_agent(crisis_country: str) -> tuple:
    """
    Rule-based scoring: extract impacted suppliers directly from the graph + ownership
    and score them deterministically.
    """
    impacted: dict = {}
    target_lower = crisis_country.lower()

    for edge in NEO4J_GRAPH:
        t1_name = edge.get("tier1")
        t2_name = edge.get("tier2")
        t1_ctry = str(edge.get("t1_country", "")).lower()
        t2_ctry = str(edge.get("t2_country", "")).lower()

        if t1_name and target_lower in t1_ctry:
            impacted[t1_name] = {
                "name": t1_name, "country": edge.get("t1_country"),
                "component": edge.get("component", "Critical Components"),
                "vehicle":   edge.get("vehicle", "Defense Systems"),
                "risk_score": 95,
                "risk_reason": f"Tier 1 supplier directly in active crisis zone ({edge.get('t1_country')}).",
                "is_sole_source": True, "tier": 1,
            }

        if t2_name and target_lower in t2_ctry and t2_name not in impacted:
            impacted[t2_name] = {
                "name": t2_name, "country": edge.get("t2_country"),
                "component": edge.get("component", "Sub-assemblies / Materials"),
                "vehicle":   edge.get("vehicle", "Defense Systems"),
                "risk_score": 85,
                "risk_reason": f"Upstream Tier 2 bottleneck in crisis country ({edge.get('t2_country')}).",
                "is_sole_source": False, "tier": 2,
            }

    # Cross-reference ownership: flag suppliers owned from crisis country
    for supplier_name, entries in OWNERSHIP_REGISTRY.items():
        if supplier_name in impacted:
            continue
        for entry in entries:
            owner_ctry = str(entry.get("country", "")).lower()
            if target_lower in owner_ctry:
                impacted[supplier_name] = {
                    "name": supplier_name, "country": entry.get("country"),
                    "component": "System Subcomponents", "vehicle": "Defense Systems",
                    "risk_score": 70,
                    "risk_reason": f"Ownership ties to {entry.get('country')} flagged.",
                    "is_sole_source": False, "tier": 1,
                }
                break

    supplier_list = list(impacted.values())
    portfolio_score = min(100, len(supplier_list) * 25) if supplier_list else 0
    risk_level = (
        "CRITICAL" if portfolio_score >= 70
        else "HIGH"   if portfolio_score >= 50
        else "MEDIUM" if portfolio_score > 0
        else "LOW"
    )

    # Build alternate suppliers with varied cost premiums (not a flat 12%)
    alternate_country = "India"
    alternates = []
    for s in supplier_list:
        alt_name = f"Domestic Alternative (India) — {s['component'][:30]}"
        cost_pct = _cost_premium_pct(s["name"], alternate_country)
        alternates.append({
            "replaces":         s["name"],
            "name":             alt_name,
            "country":          alternate_country,
            "readiness_score":  75,
            "lead_time_weeks":  6,
            "cost_premium_pct": cost_pct,
            "reason":           "Geographically secure substitute with existing capacity.",
        })

    baseline_analysis = {
        "scenario_summary": f"Geopolitical risk evaluation for dependencies in {crisis_country}.",
        "crisis_countries": [crisis_country],
        "overall_risk_level": risk_level,
        "portfolio_risk_score": portfolio_score,
        "executive_summary": (
            f"Identified {len(supplier_list)} defense nodes tied to operational "
            f"vulnerabilities within {crisis_country}."
        ),
        "suppliers": supplier_list,
        "critical_alerts": [f"Vulnerability warning for {s['name']}." for s in supplier_list],
        "immediate_actions": [
            "Engage domestic ordnance alternatives.",
            "Check safety buffer inventory allocations.",
            "Initiate dual-sourcing assessment for critical components.",
        ],
        "alternate_suppliers": alternates,
        "signals_detected": len(supplier_list),
    }
    ownership = run_ownership_analysis(supplier_list, OWNERSHIP_REGISTRY, OWNERSHIP_DEPTH_PCT)
    return baseline_analysis, ownership


# ── CELL 12: Run pipeline ─────────────────────────────────────
def run_agent(scenario: str):
    """
    Full pipeline:
      1. Run deterministic baseline scoring.
      2. Run ownership analysis.
      3. Render Plotly dashboard.
    """
    print("=" * 70)
    print(f"  🇮🇳 {AGENT_TITLE.upper()}")
    print(f"  Ownership Depth: ≥{OWNERSHIP_DEPTH_PCT}%")
    print(f"  Graph edges    : {len(NEO4J_GRAPH)}   |   Suppliers: {len(SUPPLIER_ROLLUP)}")
    print(f"  Scenario       : {scenario[:70]}...")
    print("=" * 70)

    print("\n⚙️  Step 1/2 — Deterministic baseline scoring...")
    analysis, _ = run_baseline_country_agent(crisis_country=scenario.split()[0])
    print(f"  ↳ {len(analysis['suppliers'])} suppliers scored | Risk level: {analysis['overall_risk_level']}")

    print(f"\n🏛️  Step 2/2 — Ownership analysis (≥{OWNERSHIP_DEPTH_PCT}%)...")
    ownership_data = run_ownership_analysis(analysis.get("suppliers", []), OWNERSHIP_REGISTRY, OWNERSHIP_DEPTH_PCT)
    print(f"  ↳ SOE flags: {sum(1 for o in ownership_data if o.get('soe_flag'))}")
    print(f"  ↳ State-linked owners: {sum(len(o.get('state_owners', [])) for o in ownership_data)}")

    print("\n📊 Rendering interactive Plotly dashboard...")
    render_dashboard(analysis, ownership_data)
    print("\n✅ Agent run complete.")
    return analysis, ownership_data


# ── CELL 13: Entry point ──────────────────────────────────────
SCENARIO = f"{CRISIS_COUNTRY} supply disruption — geopolitical crisis affecting Indian Army supply chain"

analysis, ownership_data = run_agent(SCENARIO)